# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 714c503ff5d24001f21249e37f92789b51a4686ad481077ce54e681c2a95e566b5125425550c5e5ed9acf58c2e198eb010a5c51ddab0fbfbd0417af17063986c

test:
  secret_key_base: 1bd7a6fd39afe83ba56cafd72ecd65c32dd6490d09b038ff1735e5b25ba3411eaaa8c8a607a3c9fb3d2358accf09981797d7ae90084d16bb0c9dfb9e83ddb782

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
